[package]
name = "polywag"
version = "0.1.0"
edition = "2024"

[dependencies]
pastey = "0.2.3"
wide = "1.4.0"
cfg-if = "1.0.4"
bytemuck = "1.25.0"



[dev-dependencies]
approx = "0.5.1"
f256 = { version = "0.11.2", default-features = false }
criterion = {version = "0.8.2", features = ["html_reports"]}


[[bench]]
name = "bench_fit"
harness = false
